// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/pb/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_BID              Side = 1
	Side_ASK              Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "BID",
		2: "ASK",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"BID":              1,
		"ASK":              2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pb_order_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_api_pb_order_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_api_pb_order_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_LIMIT                  OrderType = 1
	OrderType_MARKET                 OrderType = 2
	OrderType_IOC                    OrderType = 3
	OrderType_FOK                    OrderType = 4
	OrderType_POST_ONLY              OrderType = 5
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "LIMIT",
		2: "MARKET",
		3: "IOC",
		4: "FOK",
		5: "POST_ONLY",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"LIMIT":                  1,
		"MARKET":                 2,
		"IOC":                    3,
		"FOK":                    4,
		"POST_ONLY":              5,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_pb_order_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_api_pb_order_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_api_pb_order_proto_rawDescGZIP(), []int{1}
}

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          Side                   `protobuf:"varint,1,opt,name=side,proto3,enum=loki.pb.Side" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,2,opt,name=type,proto3,enum=loki.pb.OrderType" json:"type,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Qty           int64                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	UserId        uint64                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_api_pb_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_order_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PlaceOrderRequest) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *PlaceOrderRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SeqId         uint64                 `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_api_pb_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_order_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlaceOrderResponse) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Side          Side                   `protobuf:"varint,2,opt,name=side,proto3,enum=loki.pb.Side" json:"side,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_api_pb_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_order_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *CancelOrderRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_api_pb_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_order_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_api_pb_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_order_proto_rawDescGZIP(), []int{4}
}

type OrderEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Side          Side                   `protobuf:"varint,2,opt,name=side,proto3,enum=loki.pb.Side" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,3,opt,name=type,proto3,enum=loki.pb.OrderType" json:"type,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Qty           int64                  `protobuf:"varint,5,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEntry) Reset() {
	*x = OrderEntry{}
	mi := &file_api_pb_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEntry) ProtoMessage() {}

func (x *OrderEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEntry.ProtoReflect.Descriptor instead.
func (*OrderEntry) Descriptor() ([]byte, []int) {
	return file_api_pb_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderEntry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderEntry) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *OrderEntry) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *OrderEntry) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderEntry) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderEntry          `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_api_pb_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_order_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotResponse) GetOrders() []*OrderEntry {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_api_pb_order_proto protoreflect.FileDescriptor

const file_api_pb_order_proto_rawDesc = "" +
	"\n" +
	"\x12api/pb/order.proto\x12\aloki.pb\"\x9f\x01\n" +
	"\x11PlaceOrderRequest\x12!\n" +
	"\x04side\x18\x01 \x01(\x0e2\r.loki.pb.SideR\x04side\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.loki.pb.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x03R\x03qty\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x04R\x06userId\"C\n" +
	"\x12PlaceOrderResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x15\n" +
	"\x06seq_id\x18\x02 \x01(\x04R\x05seqId\"h\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12!\n" +
	"\x04side\x18\x02 \x01(\x0e2\r.loki.pb.SideR\x04side\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"-\n" +
	"\x13CancelOrderResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x11\n" +
	"\x0fSnapshotRequest\"\x8f\x01\n" +
	"\n" +
	"OrderEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\x04side\x18\x02 \x01(\x0e2\r.loki.pb.SideR\x04side\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.loki.pb.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x10\n" +
	"\x03qty\x18\x05 \x01(\x03R\x03qty\"?\n" +
	"\x10SnapshotResponse\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.loki.pb.OrderEntryR\x06orders*.\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03BID\x10\x01\x12\a\n" +
	"\x03ASK\x10\x02*_\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LIMIT\x10\x01\x12\n" +
	"\n" +
	"\x06MARKET\x10\x02\x12\a\n" +
	"\x03IOC\x10\x03\x12\a\n" +
	"\x03FOK\x10\x04\x12\r\n" +
	"\tPOST_ONLY\x10\x052\xe3\x01\n" +
	"\fOrderService\x12E\n" +
	"\n" +
	"PlaceOrder\x12\x1a.loki.pb.PlaceOrderRequest\x1a\x1b.loki.pb.PlaceOrderResponse\x12H\n" +
	"\vCancelOrder\x12\x1b.loki.pb.CancelOrderRequest\x1a\x1c.loki.pb.CancelOrderResponse\x12B\n" +
	"\vGetSnapshot\x12\x18.loki.pb.SnapshotRequest\x1a\x19.loki.pb.SnapshotResponseB\vZ\tapi/pb;pbb\x06proto3"

var (
	file_api_pb_order_proto_rawDescOnce sync.Once
	file_api_pb_order_proto_rawDescData []byte
)

func file_api_pb_order_proto_rawDescGZIP() []byte {
	file_api_pb_order_proto_rawDescOnce.Do(func() {
		file_api_pb_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pb_order_proto_rawDesc), len(file_api_pb_order_proto_rawDesc)))
	})
	return file_api_pb_order_proto_rawDescData
}

var file_api_pb_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_pb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_pb_order_proto_goTypes = []any{
	(Side)(0),                   // 0: loki.pb.Side
	(OrderType)(0),              // 1: loki.pb.OrderType
	(*PlaceOrderRequest)(nil),   // 2: loki.pb.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),  // 3: loki.pb.PlaceOrderResponse
	(*CancelOrderRequest)(nil),  // 4: loki.pb.CancelOrderRequest
	(*CancelOrderResponse)(nil), // 5: loki.pb.CancelOrderResponse
	(*SnapshotRequest)(nil),     // 6: loki.pb.SnapshotRequest
	(*OrderEntry)(nil),          // 7: loki.pb.OrderEntry
	(*SnapshotResponse)(nil),    // 8: loki.pb.SnapshotResponse
}
var file_api_pb_order_proto_depIdxs = []int32{
	0, // 0: loki.pb.PlaceOrderRequest.side:type_name -> loki.pb.Side
	1, // 1: loki.pb.PlaceOrderRequest.type:type_name -> loki.pb.OrderType
	0, // 2: loki.pb.CancelOrderRequest.side:type_name -> loki.pb.Side
	0, // 3: loki.pb.OrderEntry.side:type_name -> loki.pb.Side
	1, // 4: loki.pb.OrderEntry.type:type_name -> loki.pb.OrderType
	7, // 5: loki.pb.SnapshotResponse.orders:type_name -> loki.pb.OrderEntry
	2, // 6: loki.pb.OrderService.PlaceOrder:input_type -> loki.pb.PlaceOrderRequest
	4, // 7: loki.pb.OrderService.CancelOrder:input_type -> loki.pb.CancelOrderRequest
	6, // 8: loki.pb.OrderService.GetSnapshot:input_type -> loki.pb.SnapshotRequest
	3, // 9: loki.pb.OrderService.PlaceOrder:output_type -> loki.pb.PlaceOrderResponse
	5, // 10: loki.pb.OrderService.CancelOrder:output_type -> loki.pb.CancelOrderResponse
	8, // 11: loki.pb.OrderService.GetSnapshot:output_type -> loki.pb.SnapshotResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_pb_order_proto_init() }
func file_api_pb_order_proto_init() {
	if File_api_pb_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pb_order_proto_rawDesc), len(file_api_pb_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_order_proto_goTypes,
		DependencyIndexes: file_api_pb_order_proto_depIdxs,
		EnumInfos:         file_api_pb_order_proto_enumTypes,
		MessageInfos:      file_api_pb_order_proto_msgTypes,
	}.Build()
	File_api_pb_order_proto = out.File
	file_api_pb_order_proto_goTypes = nil
	file_api_pb_order_proto_depIdxs = nil
}
